POST http://localhost:8080/posts
X-User-Id: 4
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="post"
Content-Type: application/json

{"categoryId":1, "title":"안녕하세요1", "content":"반갑습니다2123123"}
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.png"
Content-Type: image/png  # ✅ 파일 타입 명시


< /Users/cheolhyeon/desktop/test.png
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="오잉??.png"
Content-Type: image/png  # ✅ 파일 타입 명시

< /Users/cheolhyeon/desktop/오잉??.png
--WebAppBoundary--

### GET offset 백만시 12 ~ 13초, 인덱스 설정 후 8302초, count 쿼리 변경 후 2675ms -> 정리 완료
GET localhost:8080/posts/40108576
X-User-Id: 5

### GET  바로하면 200ms , 인덱스 설정후 22ms, count 쿼리 변경후 1333ms -> 정리 완료
GET localhost:8080/posts/40108576
X-User-Id: 4

#
### 인기글 가져오기
GET http://localhost:8080/posts/hot

#
### 게시글 무한스크롤 5754ms offset 1만시 20초 ~ 29초 걸림
GET localhost:8080/posts-infinite?page=10000000
#

### 검색하기 page = 1 title, GENERAL 12356ms
GET http://localhost:8080/posts?categoryName=GENERAL&title=title

### 게시글 페이징 첫 페이지 5284ms page 1만시 25~31초 걸림 인덱스 생성 수 58ms
GET localhost:8080/posts?page=10000



