POST http://localhost:8080/posts
X-User-Id: 4
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="post"
Content-Type: application/json

{"categoryId":1, "title":"안녕하세요1", "content":"반갑습니다2123123"}
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.png"
Content-Type: image/png  # ✅ 파일 타입 명시


< /Users/cheolhyeon/desktop/test.png
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="오잉??.png"
Content-Type: image/png  # ✅ 파일 타입 명시

< /Users/cheolhyeon/desktop/오잉??.png
--WebAppBoundary--

### 게시글 무한스크롤 5754ms
GET localhost:8080/posts-infinite

### 게시글 페이징 5284ms offset 1만시 25초 걸림
GET localhost:8080/posts?page=10000

### GET offset 백만시 12 ~ 13초, 바로하면 200
GET localhost:8080/posts/40108576?page=1000000
X-User-Id: 4

### 인기글 가져오기
GET http://localhost:8080/posts/hot

### 검색하기 page = 1 검색 8초 offset 늘어날 수록 증가 offset30에서 14초걸림
GET http://localhost:8080/posts?page=30&title=title


