POST http://localhost:8080/posts
X-User-Id: 4
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="post"
Content-Type: application/json

{"categoryId":1, "title":"안녕하세요1", "content":"반갑습니다2123123"}
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.png"
Content-Type: image/png  # ✅ 파일 타입 명시


< /Users/cheolhyeon/desktop/test.png
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="오잉??.png"
Content-Type: image/png  # ✅ 파일 타입 명시

< /Users/cheolhyeon/desktop/오잉??.png
--WebAppBoundary--

### GET 무한스크롤
GET localhost:8080/posts-infinite

### GET 페이징
GET localhost:8080/posts

### GET
GET localhost:8080/posts/5
X-User-Id: 4

### 인기글 가져오기
GET http://localhost:8080/posts/hot

