spring:
  application:
    name: free_community
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/free_community?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 20MB

image:
  base-path: "/Users/cheolhyeon/desktop"
